### ISSUE TITLE
Updating cleaned field

### ISSUE THREAD

**Issue by tyhhytfirebird9** [piercerod57/AirBNBBackend#6]
Just a quick heads up. The code for updating a cleaning’s cleaned field doesn’t appear to save the cleaning back to the database. I have written a fix for it already but still need to push it up. I will do this tomorrow morning.

**Comment by tyhhytfirebird9** [comment]
@tyhhytfirebird9 @agforeman

**Comment by agforeman** [comment]
Closed with commit e863b31008f90069efb8b60a15f7a2af9ed5b720
